#!/bin/bash

# sbompop generates Software Bill of Materials (SBOM) for 
# 100 most popular images in the Docker Hub.
# usage: sbompop

set -eo pipefail

# number of images to generate sbom for (default: 3)
num="${1:-3}"

# constants
url="https://hub.docker.com/api/content/v1/products/search?page=1&page_size=${num}&q=%2B&source=community&type=image%2Cbundle"

# main
echo "generating sbom for $num community images from Docker Hub..."
curl -sS "$url" | jq -r '.summaries[].name' | while read img; do
	echo "image: $img"
	tools/sbom $img
done