#!/bin/bash

# generates SBOM and Vulnerability report for the top
# 100 most popular images in the Docker Hub.

set -eo pipefail

# number of top images to process (default: 3)
num="${1:-3}"

# constants
url="https://hub.docker.com/api/content/v1/products/search?page=1&page_size=${num}&q=%2B&source=community&type=image%2Cbundle"

# main
echo "generating sbom and vuln report for $num community images from Docker Hub..."
curl -sS "$url" | jq -r '.summaries[].name' | while read img; do
	echo "image: $img"
	tools/report $img
done