#!/bin/bash

set -eo pipefail

# input parameters
image=$1

# validate input parameters
if [[ -z "${image}" ]]; then
  echo "image uri required"
  exit 1
fi

# constants
sbom_dir="data"
trivy_install="https://aquasecurity.github.io/trivy/v0.18.3/installation"
syft_install="https://github.com/anchore/syft"

# environment dependencies
trivy=$(which trivy) || ( echo "trivy CLI not found, see $trivy_install" && exit 1 )
syft=$(which syft) || ( echo "syft CLI not found, see $syft_install" && exit 1 )
img_name=$(echo $image | sed -e 's/[^A-Za-z0-9._-]/_/g')

# init operations
mkdir -p $sbom_dir

echo "=================================================================="
echo "Generating SBOMs for $image"
echo "=================================================================="
echo "trivy cli : ${trivy}"
echo "syft cli  : ${syft}"
echo "img name  : ${img_name}"


# generate sboms
trivy image --quiet \
            --format spdx-json \
			--no-progress \
			--list-all-pkgs \
			--output "${sbom_dir}/${img_name}-trivy-spdx.json" \
			$image

trivy image --quiet \
            --format cyclonedx \
			--no-progress \
			--list-all-pkgs \
			--output "${sbom_dir}/${img_name}-trivy-cyclonedx.json" \
			$image

syft packages $image \
			-q \
			-s AllLayers \
			-o spdx-json \
			--file "${sbom_dir}/${img_name}-syft-spdx.json"

syft packages $image \
			-q \
			-s AllLayers \
			-o cyclonedx-xml \
			--file "${sbom_dir}/${img_name}-syft-cyclonedx.xml"

syft packages $image \
			-q \
			-s AllLayers \
			-o cyclonedx-json \
			--file "${sbom_dir}/${img_name}-syft-cyclonedx.json"
