#!/bin/bash

set -euo pipefail

f=$1

# input validation
[ -z "$f" ] && echo "sbom file not provided\n" && exit 1

# dependencies
jq=$(which jq) || ( echo "jq not installed" && exit 1 )
bq=$(which bq) || ( echo "bq not installed" && exit 1 )

d=$(date +%Y-%m-%d)
n=$(basename $f .json)

cat $f | jq -r --arg d "$d" '. as $root | .packages[] as $pkg | .packages[].externalRefs[] | [ $root.name, $pkg.SPDXID, $d, $root.creationInfo.created, ($root.creationInfo.creators | join(",")), $pkg.name, ($pkg.versionInfo // "none"), $pkg.licenseConcluded, .referenceCategory, .referenceType, .referenceLocator ] | @csv' > "${n}.csv"

if [ -s "${n}.csv" ];then
    bq load \
        --project_id cloudy-labz \
        --source_format CSV \
        --time_partitioning_type MONTH \
        --max_bad_records 1000 \
        sbomer.pkg \
        "${n}.csv" \
        setup/schema/pkg.json
fi
