#!/bin/bash

set -euo pipefail

f=$1
g=${2:-latest}

# input validation
[ -z "$f" ] && echo "sbom file not provided\n" && exit 1

# dependencies
jq=$(which jq) || ( echo "jq not installed" && exit 1 )
bq=$(which bq) || ( echo "bq not installed" && exit 1 )
bq=$(which syft) || ( echo "syft not installed" && exit 1 )

d=$(date +%Y-%m-%d)
n=$(basename $f .json)
v=$(syft --version)

cat $f | jq -r \
    --arg d "$d" \
    --arg v "$v" \
    --arg g "$g" \
    '. as $root | .packages[] | [ $root.name, $g, .name, .versionInfo // "none", .SPDXID, try(.externalRefs[] | select(.referenceCategory == "PACKAGE-MANAGER") | .referenceLocator), .licenseConcluded // "none", $d, $v, $root.spdxVersion ] | @csv' > "${n}.csv"

# output
# img_name - "registry.hub.docker.com/bitnami/external-dns"
# img_version - "sha256:8407139f6c18814a91d000cdaba3aea12b6f63bd9e6791db31d58190ce73c8c7"
# pkg_name - "adduser"
# pkg_version - "3.118"
# pkg_id - "SPDXRef-Package-deb-adduser-3e9282034226b93f"
# pkg_ref - "pkg:deb/debian/adduser@3.118?arch=all&distro=debian-11"
# pkg_license - "GPL-2.0-only"
# gen_on - "2023-02-27"
# gen_by - "syft 0.73.0" 
# gen_from - "SPDX-2.3"

if [ -s "${n}.csv" ];then
    bq load \
        --project_id cloudy-labz \
        --source_format CSV \
        --time_partitioning_type MONTH \
        --max_bad_records 1000 \
        sbomer.pkg \
        "${n}.csv" \
        setup/schema/pkg.json
fi
