#!/bin/bash

set -euo pipefail

f=$1

# input validation
[ -z "$f" ] && echo "vulnerability file not provided\n" && exit 1

# dependencies
jq=$(which jq) || ( echo "jq not installed" && exit 1 )

d=$(date +%Y-%m-%d)
n=$(basename $f .json)

cat $f | jq -r --arg d "$d" '. as $root | .matches[] | [ $root.source.target.userInput, $root.source.target.manifestDigest, $d, .vulnerability.id, .vulnerability.dataSource, .vulnerability.severity, .vulnerability.fix.state, .artifact.name, .artifact.version, .artifact.language, (.artifact.cpes | join(",")), .artifact.purl, (.artifact.metadata | join(",")) ] | @csv' >> "${n}.csv"

# output columns:
# src_img
# src_sha
# gen_day
# vul_id
# vul_src
# vul_sev
# vul_state
# art_name
# art_version
# arg_lang
# art_cpes
# art_purl
# art_meta
