on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'

env:
  image_count: 20

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

    - name: Parse URL
      run: |-
        url="https://hub.docker.com/api/content/v1/products/search?page=1&page_size=${{ env.image_count }}&q=%2B&source=community&type=image%2Cbundle"
        echo "IMG_URL=$url" >> $GITHUB_ENV

    - name: Install jq
      uses: sergeysova/jq-action@v2

    - name: Execute Search
      env:
        GH_TOKEN: ${{ github.token }}
      run: |-
        curl -sS "${{ env.IMG_URL }}" | jq -r '.summaries[].name' | while read img; do
          echo "image: $img"
          gh workflow run .github/workflows/process.yaml -f image="$img"
        done
