on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  image_count: 3

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:

    - name: Parse URL
      run: |-
        url="https://hub.docker.com/api/content/v1/products/search?page=1&page_size=${{ env.image_count }}&q=%2B&source=community&type=image%2Cbundle"
        echo "IMG_URL=$url" >> $GITHUB_ENV

    - uses: sergeysova/jq-action@v2
    - name: Execute Search
      run: |-
        curl -sS "${{ env.IMG_URL }}" | jq -r '.summaries[].name' | while read img; do
          echo "image: $img"
          gh workflow run process.yaml -f image="$img"
        done
