on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to process'
        required: true

env:
  auth_provider: "projects/865303606864/locations/global/workloadIdentityPools/sbomer-github-pool/providers/github-provider"
  auth_account: "sbomer-github-actions-user@cloudy-labz.iam.gserviceaccount.com"
  target_bucket: "sbomer-cloudy-labz"

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@07978da4bdb4faa726e52dfc6b1bed63d4b56479  # v0.13.3

    - name: Install Grype
      uses: anchore/scan-action/download-grype@dafbc97d7259af88b61bd260f2fde565d0668a72  # v3.3.4

    - name: Clean Image Name
      id: image
      run: |-
        name=$(echo ${{ inputs.image }} | sed -e 's/[^A-Za-z0-9-]/-/g')
        echo "name=$name" >> $GITHUB_OUTPUT

    - name: Make SBOM file
      id: sbom
      run: |-
        set -euo pipefail
        file="sbom-${{ steps.image.outputs.name }}.json"
        syft packages -q -o spdx-json --file "$file" ${{ inputs.image }} || true
        echo "file=$file" >> $GITHUB_OUTPUT

    - name: Make Vulnerability file
      id: vuln
      run: |-
        set -euo pipefail
        file="vuln-${{ steps.image.outputs.name }}.json"
        grype -q --add-cpes-if-none -s AllLayers -o json --file "$file" ${{ inputs.image }} || true
        echo "file=$file" >> $GITHUB_OUTPUT

    - name: Auth GCP
      id: auth
      uses: google-github-actions/auth@v1  # v1.0.0
      with:
        workload_identity_provider: ${{ env.auth_provider }}
        service_account: ${{ env.auth_account }}

    - name: Install gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 418.0.0'

    - name: Install bq
      run: |-
        gcloud components install bq

    - name: Upload Files to GCS
      run: |-
        bucket="gs://${{ env.target_bucket }}/$(date +%Y-%m-%d)/"
        gcloud storage cp ${{ steps.sbom.outputs.file }} $bucket
        gcloud storage cp ${{ steps.vuln.outputs.file }} $bucket

    - name: Import SBOM to BigQuery
      run: |-
        tools/sbom2bq ${{ steps.sbom.outputs.file }}

    - name: Import Vuln to BigQuery
      run: |-
        tools/vuln2bq ${{ steps.vuln.outputs.file }}