on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to process'
        required: true

env:
  auth_provider: "projects/595203407878/locations/global/workloadIdentityPools/sbomer-github-pool/providers/github-provider"
  auth_account: "sbomer-github-actions-user@s3cme1.iam.gserviceaccount.com"
  target_bucket: "sbomer-s3cme1"

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3.5.2

    - name: Auth GCP
      id: auth
      uses: google-github-actions/auth@v1  # v1.0.0
      with:
        workload_identity_provider: ${{ env.auth_provider }}
        service_account: ${{ env.auth_account }}

    - name: Install gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 418.0.0'

    - name: Install bq
      run: |-
        gcloud components install bq

    - name: Install syft
      uses: anchore/sbom-action/download-syft@v0.14.2
      with:
        syft-version: v0.73.0

    - name: Install grype
      uses: anchore/scan-action/download-grype@v3.3.5
      with:
        grype-version: v0.57.1


    - name: Clean Name
      id: image
      run: |-
        clean_name=$(echo ${{ inputs.image }} | sed -e 's/[^A-Za-z0-9-]/-/g')
        echo "clean_name=$clean_name" >> $GITHUB_OUTPUT

    - name: Make SBOM file
      id: sbom
      run: |-
        set -euo pipefail
        file="sbom-${{ steps.image.outputs.clean_name }}.json"
        syft packages -q -o spdx-json --file "$file" ${{ inputs.image }} || true
        echo "file=$file" >> $GITHUB_OUTPUT

    - name: Make Vulnerability file
      id: vuln
      run: |-
        set -euo pipefail
        file="vuln-${{ steps.image.outputs.clean_name }}.json"
        grype -q --add-cpes-if-none -s AllLayers -o json --file "$file" ${{ inputs.image }} || true
        echo "file=$file" >> $GITHUB_OUTPUT
        digest=$(cat "$file" | jq -r 'try(.source.target.repoDigests[0] | split("@") | .[1]) // "latest"')
        echo "digest=$digest" >> $GITHUB_OUTPUT

    - name: Upload Files to GCS
      run: |-
        bucket="gs://${{ env.target_bucket }}/$(date +%Y-%m-%d)/"
        gcloud storage cp ${{ steps.sbom.outputs.file }} $bucket
        gcloud storage cp ${{ steps.vuln.outputs.file }} $bucket

    - name: Import SBOM to BigQuery
      run: |-
        tools/sbom2bq ${{ steps.sbom.outputs.file }} ${{ steps.vuln.outputs.digest }}

    - name: Import Vuln to BigQuery
      run: |-
        tools/vuln2bq ${{ steps.vuln.outputs.file }}
