name: report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  scorecard_version: "0.0.5"
  image_count: 3

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      with:
        fetch-depth: 1

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@06e109483e6aa305a2b2395eabae554e51530e1d  # v0.13.1
      with:
        version: v0.13.1

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Install SBOM Scorecard
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        gh -R eBay/sbom-scorecard \
          release download ${{ env.scorecard_version }} -p sbom-scorecard-linux-amd64
        mv sbom-scorecard-linux-amd64 sbom-scorecard
        chmod ug+x sbom-scorecard
        COMPUTED_HASH=$(sha256sum sbom-scorecard | cut -d ' ' -f1)
        EXPECTED_HASH="648c4de39e9eb7a113ac0443f1f52e914c2b77546aae20ff9d95ffd180c22b7f"
        if [[ "$EXPECTED_HASH" != "$COMPUTED_HASH" ]];then
            echo "error: expected $EXPECTED_HASH, computed $COMPUTED_HASH"
            exit 1
        fi

    - name: Generate Report
      run: |
        tools/images ${{ env.image_count }}
