name: report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  image_count: 3

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:

    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568  # v3.5.0
      with:
        go-version: '1.19.5'

    - run: go version

    - name: Cache Go Modules
      uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12  # v3.2.3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      with:
        fetch-depth: 1

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@06e109483e6aa305a2b2395eabae554e51530e1d  # v0.13.1
      with:
        version: v0.13.1

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Lint Go
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376  # v3.3.1
      with:
        version: latest

    - name: Config YAML Lint
      id: yamllint_config
      uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b  # v2.0
      with:
        files: .yamllint

    - name: Lint YAML
      if: steps.yamllint_config.outputs.files_exists == 'true'
      uses: karancode/yamllint-github-action@234e9eaa717ea611161a54e71cb027da9878f2ef  # master
      with:
        yamllint_config_filepath: .yamllint

    - name: Unit Test
      run: |
        make test

    - name: Build
      run: |
        make build

    - name: Generate SBOMs
      run: |
        tools/images ${{ env.image_count }}

    - name: Generate Report
      run: |
        bin/sbomer report -s ./data/ -o ./test.json
