name: report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      with:
        fetch-depth: 1

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@06e109483e6aa305a2b2395eabae554e51530e1d  # v0.13.1
      with:
        version: v0.13.1

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Generate Report 
      run: |
        tools/sbom-report
