on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 */8 * * *'

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

    - name: Install jq
      uses: sergeysova/jq-action@v2

    - name: Execute Search
      env:
        GH_TOKEN: ${{ github.token }}
      run: |-
        for img in ./images
        do
          echo "image: $img"
          gh workflow run .github/workflows/process.yaml -f image="$img"
        done
